apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-proxy-api-server
  namespace: <NAMESPACE>
spec:
  replicas: <NUM_REPLICAS>
  selector:
    matchLabels:
      app: elasticsearch-proxy-api
  template:
    metadata:
      labels:
        app: elasticsearch-proxy-api
    spec:
      securityContext:
        runAsUser: <UID>
        runAsGroup: <GID>
      containers:
      - name: elasticsearch-proxy-api
        image: <SERVER_IMAGE_TAG>
        imagePullPolicy: Always
        volumeMounts:
        - name: run-config
          mountPath: '/etc/run_config/'
          readOnly: true
        - name: gunicorn-config
          mountPath: '/etc/gunicorn_config/'
          readOnly: true
      volumes:
        - name: run-config
          secret:
            secretName: <RUN_CONFIG_SECRET_NAME>
        - name: gunicorn-config
          secret:
            secretName: <GUNICORN_CONFIG_SECRET_NAME>

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-proxy-api
  namespace: <NAMESPACE>
spec:
  type: NodePort
  selector:
    app: delayed-jobs
  ports:
  - port: 5000
    targetPort: 5000
