run_env: DEV # DEV, TEST, STAGING or PROD
server_secret_key: 'ServerKey'
elasticsearch:
  host: 'http://wp-p2m-50.ebi.ac.uk:9200'
cache_config:
  CACHE_TYPE: simple
base_path: ''
es_proxy_cache_seconds: 604800 # 7 days