run_env: DEV # DEV, TEST, STAGING or PROD
server_secret_key: 'ServerKey'
elasticsearch:
  host: 'some_host'
cache_config:
  CACHE_TYPE: simple
base_path: ''
es_proxy_cache_seconds: 604800 # 7 days
usage_statistics:
  cache_statistics_index: 'cache_statistics_index'